services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  query-api:
    build:
      context: ./query-stack
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - "9000:9000"

  query-consumer:
    build:
      context: ./query-stack
    command: ["python", "consumer/main.py"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGO_HOST=mongodb
    depends_on:
      - rabbitmq
      - mongodb
